# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: make-lint
        name: Execute Python linters
        entry: make lint-check
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: make-format
        name: Format Python code
        entry: make format-check
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: make-type-check
        name: Type check Python code
        entry: make type-check
        language: system
        pass_filenames: false
        stages: [pre-commit]
