[tool.poetry]
name = "bigdata-research-tools"
version = "0.3"
description = "Bigdata.com SDK Research Tools"
authors = ["Shawn Azdam <sazdam@ravenpack.com>"]

[tool.poetry.dependencies]
python = "<4.0,>=3.9"
bigdata-client = "^2.5.0"
